### PR TITLE
general: apply clippy lints

### PR DESCRIPTION
**Pull request by jxs**
updated the crates to the 2021 edition due to the new formatting lints in `panic!` and `assert!` macros.  
If preferred I can try to isolate the fixes to only assert #405 passes.

### CODE REVIEW

**Comment by algesten** [comment]
Thanks!

@k0nserv is 2021 ok or are we more conservative on the MSRV?

**Comment by k0nserv** [comment]
Yeah that's fine, current minimum target is 1.60.0 so should be fine

**Comment by algesten** [comment]
@jxs i think it wants a `cargo fmt`

**Comment by jxs** [comment]
thanks @algesten, updated!

**Review by algesten — APPROVED** [review]

**Pull request merged**
