### PR TITLE
RTCP: Add bytes crate support

### PR DESCRIPTION
**Pull request by metaclips**

### CODE REVIEW

**Comment by rainliu** [comment]
@metaclips, looks like this PR is in draft mode. are you going to update it?

**Comment by metaclips** [comment]
> @metaclips, looks like this PR is in draft mode. are you going to update it?

Yes. I made it a draft PR to avoid duplicate work.

**Comment by metaclips** [comment]
@rainliu seems session_rtp_test test fails 🙁 currently don't know why. An extra eye will be helpful.

**Comment by metaclips** [comment]
w00t. All tests passed!!

**Review by rainliu — COMMENTED** [review]
any reason switching io::Read to [u8]? Similarly, why not io::Write for marshal?

Any benefit for this kind of change?

**Comment by metaclips** [comment]
> Currently, all modules, SDP/RTP/RTCP/SRTP/DTLS use io::Read/Write for marshal and unmarshal.
> 
> any reason switching io::Read to [u8]? Similarly, why not io::Write for marshal?
> 
> Any benefit for this kind of change? My concern of this change will break the consistency of marshal/unmarshal across modules

This is to remove the amount of std libraries and also eliminate unnecessary overhead.

**Comment by metaclips** [comment]
@rainliu I can revert back to io:write if needed

**Comment by rainliu** [comment]
@metaclips, I don't mind adding new unmarshal interface with &[u8]. But io::Read/Writer interface should be kept for consistent.

**Comment by metaclips** [comment]
@rainliu I think it's best I hold this PR at least till we benchmark both Marshall/Unmarshall function.

**Comment by metaclips** [comment]
@rainliu [TestRFC8285OneByteMultipleExtensionsWithPadding](https://github.com/pion/rtp/blob/124ecad946ecbb3190897d657def6d5862958429/packet_test.go#L212) test seem to fail. In a scenario users have a padded buffer which they want to marshal data to, io::Writer appends to the buffer thereby increasing the buffer size instead of directly mutating the data.

```rust

fn test_rfc8285_one_byte_multiple_extensions_with_padding() {
    let raw_pkt: Vec<u8> = vec![
        0x90, 0xe0, 0x69, 0x8f, 0xd9, 0xc2, 0x93, 0xda, 0x1c, 0x64, 0x27, 0x82, 0xBE, 0xDE, 0x00,
        0x03, 0x10, 0xAA, 0x21, 0xBB, 0xBB, 0x00, 0x00, 0x33, 0xCC, 0xCC, 0xCC, 0xCC,
        // Payload
        0x98, 0x36, 0xbe, 0x88, 0x9e,
    ];

    let packet = Packet::unmarshal(&mut BufReader::new(raw_pkt.as_slice()))
        .expect("Error unmarshalling packets");

    let ext1 = packet
        .header
        .get_extension(1)
        .expect("Error getting header extension.");

    let ext1_expect: [u8; 1] = [0xAA];
    assert_eq!(ext1, ext1_expect);

    let ext2 = packet
        .header
        .get_extension(2)
        .expect("Error getting header extension.");

    let ext2_expect: [u8; 2] = [0xBB, 0xBB];
    assert_eq!(ext2, ext2_expect);

    let ext3 = packet
        .header
        .get_extension(3)
        .expect("Error getting header extension.");

    let ext3_expect: [u8; 4] = [0xCC, 0xCC, 0xCC, 0xCC];
    assert_eq!(ext3, ext3_expect);

    let mut dst_buf: Vec<Vec<u8>> = vec![vec![0u8; 1000], vec![0xFF; 1000]];

    let raw_pkg_marshal: [u8; 33] = [
        0x90, 0xe0, 0x69, 0x8f, 0xd9, 0xc2, 0x93, 0xda, 0x1c, 0x64, 0x27, 0x82, 0xBE, 0xDE, 0x00,
        0x03, 0x10, 0xAA, 0x21, 0xBB, 0xBB, 0x33, 0xCC, 0xCC, 0xCC, 0xCC, 0x00,
        0x00, // padding is moved to the end by re-marshaling
        // Payload
        0x98, 0x36, 0xbe, 0x88, 0x9e,
    ];

    let checker = |name: &str, mut buf: &mut Vec<u8>, p: &Packet| {
        {
            let mut writer = BufWriter::new(&mut buf);
            p.marshal(&mut writer).expect("Error marshalling byte");
        }

        println!("{:?} \n\n{}", buf, buf.len());

        assert_eq!(
            &p.payload[..p.header.payload_offset],
            &raw_pkg_marshal[..],
            "Marshalled fields are not equal for {}.",
            name
        );
    };
```

Notice it gives weird output when you directly pass an array of byte to the writer (check the checker callback function)

```rust
fn test_rfc8285_one_byte_multiple_extensions_with_padding() {
    //  0                   1                   2                   3
    //  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |       0xBE    |    0xDE       |           length=3            |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |  ID   | L=0   |     data      |  ID   |  L=1  |   data...
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    //       ...data   |    0 (pad)    |    0 (pad)    |  ID   | L=3   |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |                          data                                 |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

    let raw_pkt: Vec<u8> = vec![
        0x90, 0xe0, 0x69, 0x8f, 0xd9, 0xc2, 0x93, 0xda, 0x1c, 0x64, 0x27, 0x82, 0xBE, 0xDE, 0x00,
        0x03, 0x10, 0xAA, 0x21, 0xBB, 0xBB, 0x00, 0x00, 0x33, 0xCC, 0xCC, 0xCC, 0xCC,
        // Payload
        0x98, 0x36, 0xbe, 0x88, 0x9e,
    ];

    let packet = Packet::unmarshal(&mut BufReader::new(raw_pkt.as_slice()))
        .expect("Error unmarshalling packets");

    let ext1 = packet
        .header
        .get_extension(1)
        .expect("Error getting header extension.");

    let ext1_expect: [u8; 1] = [0xAA];
    assert_eq!(ext1, ext1_expect);

    let ext2 = packet
        .header
        .get_extension(2)
        .expect("Error getting header extension.");

    let ext2_expect: [u8; 2] = [0xBB, 0xBB];
    assert_eq!(ext2, ext2_expect);

    let ext3 = packet
        .header
        .get_extension(3)
        .expect("Error getting header extension.");

    let ext3_expect: [u8; 4] = [0xCC, 0xCC, 0xCC, 0xCC];
    assert_eq!(ext3, ext3_expect);

    let mut dst_buf: Vec<Vec<u8>> = vec![vec![0u8; 1000], vec![0xFF; 1000]];

    let raw_pkg_marshal: [u8; 33] = [
        0x90, 0xe0, 0x69, 0x8f, 0xd9, 0xc2, 0x93, 0xda, 0x1c, 0x64, 0x27, 0x82, 0xBE, 0xDE, 0x00,
        0x03, 0x10, 0xAA, 0x21, 0xBB, 0xBB, 0x33, 0xCC, 0xCC, 0xCC, 0xCC, 0x00,
        0x00, // padding is moved to the end by re-marshaling
        // Payload
        0x98, 0x36, 0xbe, 0x88, 0x9e,
    ];

    let checker = |name: &str, mut buf: &mut [u8], p: &Packet| {
        {
            let mut writer = BufWriter::new(&mut buf);
            p.marshal(&mut writer).expect("Error marshalling byte");
        }

        println!("{:?} \n\n{}", buf, buf.len());

        assert_eq!(
            &p.payload[..p.header.payload_offset],
            &raw_pkg_marshal[..],
            "Marshalled fields are not equal for {}.",
            name
        );
    };

    checker("CleanBuffer", &mut dst_buf[0], &packet);
    checker("DirtyBuffer", &mut dst_buf[1], &packet);
}
```

**Comment by rainliu** [comment]
@metaclips , for test case, test_rfc8285_one_byte_multiple_extensions_with_padding, you can take a look at the commit how to handle pre-allocated buf with BufWriter.

https://github.com/webrtc-rs/webrtc/commit/8b3dea8b177807fc799fae346b101d376b49e189

For BufWriter, if you uses
```
let mut writer = BufWriter::new(&mut buf);
or 
let mut writer = BufWriter::<&mut Vec<u8>>::new(dst.as_mut());
```
BufWriter will append data to the Vec buffer.

If you uses
```
let mut writer = BufWriter::new(buf.as_mut_slice());
``
BufWriter will mutate the buffer data, but the drawback is that if buffer is not big enough, BufWriter won't increase the buffer size.

**Comment by metaclips** [comment]
> @metaclips , for test case, test_rfc8285_one_byte_multiple_extensions_with_padding, you can take a look at the commit how to handle pre-allocated buf with BufWriter.
> 
> [8b3dea8](https://github.com/webrtc-rs/webrtc/commit/8b3dea8b177807fc799fae346b101d376b49e189)
> 
> For BufWriter, if you uses
> 
> ```
> let mut writer = BufWriter::new(&mut buf);
> or 
> let mut writer = BufWriter::<&mut Vec<u8>>::new(dst.as_mut());
> ```
> 
> BufWriter will append data to the Vec buffer.
> 
> If you uses
> 
> ```
> let mut writer = BufWriter::new(buf.as_mut_slice());
> ```
> 
> BufWriter will mutate the buffer data, but the drawback is that if buffer is not big enough, BufWriter won't increase the buffer size.

Indeed. The recent code samples were test cases users could shoot theirselves in the foot since the code is syntactically correct. We shouldn't allow errors from any sort especially from users ensuring all libraries are also fool proof.

**Comment by metaclips** [comment]
@rainliu I'll suggest deprecating std::io::write for byte slice

**Comment by rainliu** [comment]
> @rainliu I'll suggest deprecating std::io::write for byte slice

I created a issue #27 to track this problem.

**Comment by metaclips** [comment]
@rainliu I'll continue contributing to this PR. All tests written as of now passed.

**Comment by metaclips** [comment]
@rainliu  I can also take up the task to change all other marshal/unmarshal convention to byte slice in a different PR.

**Comment by rainliu** [comment]
@metaclips , I think I found the way to handle the issue #27 .

Please check the commit https://github.com/webrtc-rs/webrtc/commit/11d5fd22ec8419f96c0c191bb6e9ed19477b8f55

**Comment by metaclips** [comment]
@rainliu I really don't think the commit fixes the issue, here's a test case that fails. This code is syntactically correct.

```rust
 fn test_rfc8285_one_byte_multiple_extensions_with_padding() {
    //  0                   1                   2                   3
    //  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |       0xBE    |    0xDE       |           length=3            |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |  ID   | L=0   |     data      |  ID   |  L=1  |   data...
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    //       ...data   |    0 (pad)    |    0 (pad)    |  ID   | L=3   |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |                          data                                 |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

    let raw_pkt: Vec<u8> = vec![
        0x90, 0xe0, 0x69, 0x8f, 0xd9, 0xc2, 0x93, 0xda, 0x1c, 0x64, 0x27, 0x82, 0xBE, 0xDE, 0x00,
        0x03, 0x10, 0xAA, 0x21, 0xBB, 0xBB, 0x00, 0x00, 0x33, 0xCC, 0xCC, 0xCC, 0xCC,
        // Payload
        0x98, 0x36, 0xbe, 0x88, 0x9e,
    ];

    let packet = Packet::unmarshal(&mut BufReader::new(raw_pkt.as_slice()))
        .expect("Error unmarshalling packets");

    let ext1 = packet
        .header
        .get_extension(1)
        .expect("Error getting header extension.");

    let ext1_expect: [u8; 1] = [0xAA];
    assert_eq!(ext1, ext1_expect);

    let ext2 = packet
        .header
        .get_extension(2)
        .expect("Error getting header extension.");

    let ext2_expect: [u8; 2] = [0xBB, 0xBB];
    assert_eq!(ext2, ext2_expect);

    let ext3 = packet
        .header
        .get_extension(3)
        .expect("Error getting header extension.");

    let ext3_expect: [u8; 4] = [0xCC, 0xCC, 0xCC, 0xCC];
    assert_eq!(ext3, ext3_expect);

    let mut dst_buf = [[0u8; 1000], [0xFF; 1000]];

    let raw_pkg_marshal: [u8; 33] = [
        0x90, 0xe0, 0x69, 0x8f, 0xd9, 0xc2, 0x93, 0xda, 0x1c, 0x64, 0x27, 0x82, 0xBE, 0xDE, 0x00,
        0x03, 0x10, 0xAA, 0x21, 0xBB, 0xBB, 0x33, 0xCC, 0xCC, 0xCC, 0xCC, 0x00, 0x00,
        // padding is moved to the end by re-marshaling
        // Payload
        0x98, 0x36, 0xbe, 0x88, 0x9e,
    ];

    let checker = |name: &str, mut buf: &mut [u8], p: &Packet| {
        {
            // NOTE: buf.as_mut_slice() won't increase buf size.
            // If buf size is not big enough, it will be silent and won't report error
            let mut writer = BufWriter::new(&mut buf);
            p.marshal(&mut writer).expect("Error marshalling byte");
        }

        println!("{:?}", &buf);

        assert_eq!(
            &buf[..p.size()],
            &raw_pkg_marshal[..],
            "Marshalled fields are not equal for {}.",
            name
        );
    };

    checker("CleanBuffer", &mut dst_buf[0], &packet);
    checker("DirtyBuffer", &mut dst_buf[1], &packet);
}
```

Here's another test case which is syntactically correct.

```rust
#[test]
fn test_rfc8285_one_byte_multiple_extensions_with_padding() {
    //  0                   1                   2                   3
    //  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |       0xBE    |    0xDE       |           length=3            |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |  ID   | L=0   |     data      |  ID   |  L=1  |   data...
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    //       ...data   |    0 (pad)    |    0 (pad)    |  ID   | L=3   |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |                          data                                 |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

    let raw_pkt: Vec<u8> = vec![
        0x90, 0xe0, 0x69, 0x8f, 0xd9, 0xc2, 0x93, 0xda, 0x1c, 0x64, 0x27, 0x82, 0xBE, 0xDE, 0x00,
        0x03, 0x10, 0xAA, 0x21, 0xBB, 0xBB, 0x00, 0x00, 0x33, 0xCC, 0xCC, 0xCC, 0xCC,
        // Payload
        0x98, 0x36, 0xbe, 0x88, 0x9e,
    ];

    let packet = Packet::unmarshal(&mut BufReader::new(raw_pkt.as_slice()))
        .expect("Error unmarshalling packets");

    let ext1 = packet
        .header
        .get_extension(1)
        .expect("Error getting header extension.");

    let ext1_expect: [u8; 1] = [0xAA];
    assert_eq!(ext1, ext1_expect);

    let ext2 = packet
        .header
        .get_extension(2)
        .expect("Error getting header extension.");

    let ext2_expect: [u8; 2] = [0xBB, 0xBB];
    assert_eq!(ext2, ext2_expect);

    let ext3 = packet
        .header
        .get_extension(3)
        .expect("Error getting header extension.");

    let ext3_expect: [u8; 4] = [0xCC, 0xCC, 0xCC, 0xCC];
    assert_eq!(ext3, ext3_expect);

    let mut dst_buf = [vec![0u8; 1000], vec![0xFF; 1000]];

    let raw_pkg_marshal: [u8; 33] = [
        0x90, 0xe0, 0x69, 0x8f, 0xd9, 0xc2, 0x93, 0xda, 0x1c, 0x64, 0x27, 0x82, 0xBE, 0xDE, 0x00,
        0x03, 0x10, 0xAA, 0x21, 0xBB, 0xBB, 0x33, 0xCC, 0xCC, 0xCC, 0xCC, 0x00, 0x00,
        // padding is moved to the end by re-marshaling
        // Payload
        0x98, 0x36, 0xbe, 0x88, 0x9e,
    ];

    let checker = |name: &str, mut buf: &mut Vec<u8>, p: &Packet| {
        {
            // NOTE: buf.as_mut_slice() won't increase buf size.
            // If buf size is not big enough, it will be silent and won't report error
            let mut writer = BufWriter::new(&mut buf);
            p.marshal(&mut writer).expect("Error marshalling byte");
        }

        println!("{:?}", &buf);

        assert_eq!(
            &buf[..p.size()],
            &raw_pkg_marshal[..],
            "Marshalled fields are not equal for {}.",
            name
        );
    };

    checker("CleanBuffer", &mut dst_buf[0], &packet);
    checker("DirtyBuffer", &mut dst_buf[1], &packet);
}
```

Notice for the first test, nothing is written to the buffer when you print but, while for the second, data is appended to the vec which shouldn't be so (data should be prepended to instead). Also, note that if buffer is short (when memory size is denoted as 0 instead of 1000, there is no definite error handling, current code doesn't return a short buffer error.

This is another test case that fails when vec is of 0 size (vec should grow as it's heap allocated).

```rust
#[test]
fn test_rfc8285_one_byte_multiple_extensions_with_padding() {
    //  0                   1                   2                   3
    //  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |       0xBE    |    0xDE       |           length=3            |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |  ID   | L=0   |     data      |  ID   |  L=1  |   data...
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    //       ...data   |    0 (pad)    |    0 (pad)    |  ID   | L=3   |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |                          data                                 |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

    let raw_pkt: Vec<u8> = vec![
        0x90, 0xe0, 0x69, 0x8f, 0xd9, 0xc2, 0x93, 0xda, 0x1c, 0x64, 0x27, 0x82, 0xBE, 0xDE, 0x00,
        0x03, 0x10, 0xAA, 0x21, 0xBB, 0xBB, 0x00, 0x00, 0x33, 0xCC, 0xCC, 0xCC, 0xCC,
        // Payload
        0x98, 0x36, 0xbe, 0x88, 0x9e,
    ];

    let packet = Packet::unmarshal(&mut BufReader::new(raw_pkt.as_slice()))
        .expect("Error unmarshalling packets");

    let ext1 = packet
        .header
        .get_extension(1)
        .expect("Error getting header extension.");

    let ext1_expect: [u8; 1] = [0xAA];
    assert_eq!(ext1, ext1_expect);

    let ext2 = packet
        .header
        .get_extension(2)
        .expect("Error getting header extension.");

    let ext2_expect: [u8; 2] = [0xBB, 0xBB];
    assert_eq!(ext2, ext2_expect);

    let ext3 = packet
        .header
        .get_extension(3)
        .expect("Error getting header extension.");

    let ext3_expect: [u8; 4] = [0xCC, 0xCC, 0xCC, 0xCC];
    assert_eq!(ext3, ext3_expect);

    let mut dst_buf = [vec![0u8; 0], vec![0xFF; 0]];

    let raw_pkg_marshal: [u8; 33] = [
        0x90, 0xe0, 0x69, 0x8f, 0xd9, 0xc2, 0x93, 0xda, 0x1c, 0x64, 0x27, 0x82, 0xBE, 0xDE, 0x00,
        0x03, 0x10, 0xAA, 0x21, 0xBB, 0xBB, 0x33, 0xCC, 0xCC, 0xCC, 0xCC, 0x00, 0x00,
        // padding is moved to the end by re-marshaling
        // Payload
        0x98, 0x36, 0xbe, 0x88, 0x9e,
    ];

    let checker = |name: &str, buf: &mut Vec<u8>, p: &Packet| {
        {
            // NOTE: buf.as_mut_slice() won't increase buf size.
            // If buf size is not big enough, it will be silent and won't report error
            let mut writer = BufWriter::new(buf.as_mut_slice());
            p.marshal(&mut writer).expect("Error marshalling byte");
        }

        println!("{:?}", &buf);

        assert_eq!(
            &buf[..p.size()],
            &raw_pkg_marshal[..],
            "Marshalled fields are not equal for {}.",
            name
        );
    };

    checker("CleanBuffer", &mut dst_buf[0], &packet);
    checker("DirtyBuffer", &mut dst_buf[1], &packet);
}
```

I'll suggest we use a simple byte array which should be fast enough or, use [bytes crate](https://docs.rs/bytes/0.6.0/bytes/)

**Comment by metaclips** [comment]
@rainliu I just benchmarked using writer against byte slice. Here's the result

For byte slice
```
     Running target/release/deps/benches-9c68b62ebd413779
Gnuplot not found, using plotters backend
rtp::unmarshal          time:   [640.97 ns 660.67 ns 682.86 ns]                            
                        change: [-0.1772% +1.8001% +4.1706%] (p = 0.09 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  8 (8.00%) high severe

rtp::marshal            time:   [958.46 ns 968.64 ns 979.98 ns]                          
                        change: [-1.7906% -0.1436% +1.5639%] (p = 0.86 > 0.05)
                        No change in performance detected.
Found 6 outliers among 100 measurements (6.00%)
```

For writer

```
     Running target/release/deps/benches-704605bc60903a24
Gnuplot not found, using plotters backend
rtp::marshal            time:   [1.0861 us 1.0971 us 1.1096 us]                          
                        change: [-3.6303% -1.9657% +0.5494%] (p = 0.04 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high severe

rtp::unmarshal          time:   [676.38 ns 682.10 ns 688.15 ns]                            
                        change: [-2.6076% -1.2608% +0.0248%] (p = 0.06 > 0.05)
                        No change in performance detected.
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe
```

**Comment by rainliu** [comment]
@metaclips , I like the idea using bytes crate.

**Comment by metaclips** [comment]
@rainliu I'll continue this PR adding bytes crate support

**Comment by metaclips** [comment]
> @rainliu I just benchmarked using writer against byte slice. Here's the result
> 
> For byte slice
> 
> ```
>      Running target/release/deps/benches-9c68b62ebd413779
> Gnuplot not found, using plotters backend
> rtp::unmarshal          time:   [640.97 ns 660.67 ns 682.86 ns]                            
>                         change: [-0.1772% +1.8001% +4.1706%] (p = 0.09 > 0.05)
>                         No change in performance detected.
> Found 8 outliers among 100 measurements (8.00%)
>   8 (8.00%) high severe
> 
> rtp::marshal            time:   [958.46 ns 968.64 ns 979.98 ns]                          
>                         change: [-1.7906% -0.1436% +1.5639%] (p = 0.86 > 0.05)
>                         No change in performance detected.
> Found 6 outliers among 100 measurements (6.00%)
> ```
> 
> For writer
> 
> ```
>      Running target/release/deps/benches-704605bc60903a24
> Gnuplot not found, using plotters backend
> rtp::marshal            time:   [1.0861 us 1.0971 us 1.1096 us]                          
>                         change: [-3.6303% -1.9657% +0.5494%] (p = 0.04 < 0.05)
>                         Change within noise threshold.
> Found 4 outliers among 100 measurements (4.00%)
>   4 (4.00%) high severe
> 
> rtp::unmarshal          time:   [676.38 ns 682.10 ns 688.15 ns]                            
>                         change: [-2.6076% -1.2608% +0.0248%] (p = 0.06 > 0.05)
>                         No change in performance detected.
> Found 3 outliers among 100 measurements (3.00%)
>   2 (2.00%) high mild
>   1 (1.00%) high severe
> ```

@rainliu using bytes crate on rtp marshal/unmarshal here is the benchmark result
```
     Running target/release/deps/benches-fec1500ad760b941
Gnuplot not found, using plotters backend
rtp::unmarshal          time:   [504.29 ns 510.30 ns 516.65 ns]                            
                        change: [-32.092% -30.959% -29.787%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high severe

rtp::marshal            time:   [802.29 ns 806.67 ns 811.47 ns]                          
                        change: [-17.796% -16.387% -15.097%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  6 (6.00%) high mild
  3 (3.00%) high severe
```

**Comment by rainliu** [comment]
@metaclips, it looks like your changes are quite big for this bytes crate support.

Could you split this pull request into multiple PRs separated by SDP, RTP, RTCP, SRTP, etc? So, it is easy for review.

Thanks.

**Comment by metaclips** [comment]
@rainliu I'll suggest we submit this patches to a different branch till we are done converting all crates to bytes.

**Comment by rainliu** [comment]
@metaclips, sounds good to me with a different branch.

**Comment by metaclips** [comment]
@rainliu do create a new branch so I can point my PR to it.

**Comment by rainliu** [comment]
@metaclips, bytes branch is created.

**Comment by metaclips** [comment]
@rainliu I'll be consuming all bytes sent for unmarshalling.[This is so due to bytes being mutated when unmarshalling](https://github.com/metaclips/webrtc/blob/b6b04b220596363b744e3597dfa5732d18e02a72/rtcp/src/compound_packet/mod.rs#L122) bytes will be consumed and if users want to retain a copy, they can clone.

**Comment by metaclips** [comment]
Fixed in 4be54e1

**Comment by metaclips** [comment]
@rainliu pr is ready

**Pull request merged**
