### PR TITLE
Adjust some rustfmt configurations

### LINKED ISSUE #397: Adjust rustfmt configuration
I want to make the following changes to the rustfmt configuration of the repo, I wonder if the maintainer can accept it?

```toml
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
```

### PR DESCRIPTION
**Pull request by koushiro**
rustfmt.toml

```toml
imports_granularity = "Module"
group_imports = "StdExternalCrate"
```

close #397 

I'm not sure if there are other configurations that need to be changed 😕

### CODE REVIEW

**Comment by rainliu** [comment]
@koushiro , could you rebase to resolve conflicts? thanks.

**Comment by koushiro** [comment]
> @koushiro , could you rebase to resolve conflicts? thanks.

Done

**Review by melekes — APPROVED** [review]
👍

**Comment by melekes** [comment]
@koushiro can you please rebase against master? it might be easier to close this PR and open a new one.

**Comment by melekes** [comment]
Closing in favor of https://github.com/webrtc-rs/webrtc/pull/462. Thanks @koushiro 🙇

**Pull request closed without merging**
