### PR TITLE
[DTLS] Add NamedCurve::P384

### PR DESCRIPTION
**Pull request by neonphog**
related: https://github.com/webrtc-rs/webrtc/issues/24

Migrated from existing PR in multi-repo: https://github.com/webrtc-rs/dtls/pull/21

@k0nserv @rainliu @melekes

### CODE REVIEW

**Review by k0nserv — APPROVED** [review]

**Review by algesten — APPROVED** [review]
LGTM

**Comment by k0nserv** [comment]
@neonphog could you rebase on master so we can get a better idea of CI?

**Comment by neonphog** [comment]
@k0nserv 

> @neonphog could you rebase on master so we can get a better idea of CI please?

yep : ) done :+1:

**Comment by k0nserv** [comment]
I cancelled the windows runs since they are fixed upstream on master.

**Review by melekes — COMMENTED** [review]
lgtm 👍

**Pull request merged**
