### PR TITLE
Fix over-NACK due to NackPair lost_packets not resetting

### PR DESCRIPTION
**Pull request by kraigher**

### CODE REVIEW

**Comment by kraigher** [comment]
The corresponding Pion code is here:
https://github.com/pion/rtcp/blob/fb051e52c7e07977197f542741ae912792defd77/transport_layer_nack.go#L38

**Comment by k0nserv** [comment]
Very nice. So we had been over-NACKing before. This is a good result. 

Can you add a changelog entry in `interceptor/CHANGELOG.md` under unreleased please?

**Comment by kraigher** [comment]
Yes I will add the entry later today.

**Comment by kraigher** [comment]
I updated the requested changelogs and crate versions as well

**Comment by k0nserv** [comment]
Thanks @kraigher

**Pull request merged**
