### PR TITLE
Fix `cargo fmt` error

### PR DESCRIPTION
**Pull request by TaKO8Ki**
closes https://github.com/webrtc-rs/webrtc/issues/5

reference: https://github.com/rust-lang/rustfmt/issues/3666

### CODE REVIEW

**Comment by TaKO8Ki** [comment]
@rainliu 
I've fixed https://github.com/webrtc-rs/webrtc/issues/5!

**Comment by rainliu** [comment]
thanks for the fix.

**Comment by rainliu** [comment]
looks like still failure.

**Comment by TaKO8Ki** [comment]
@rainliu 
I don't think this failure has anything to do with https://github.com/webrtc-rs/webrtc/issues/5.
`cargo fmt` works well.
https://github.com/webrtc-rs/webrtc/runs/1337796325?check_suite_focus=true

**Comment by rainliu** [comment]
sorry, my fault. I just removed state.rs to get cargo fmt pass.

**Comment by TaKO8Ki** [comment]
@rainliu 
Thank you!

**Comment by TaKO8Ki** [comment]
@rainliu 
Should I reopen my pull request?

**Comment by rainliu** [comment]
no need, I put your changes in the latest commit.

**Pull request merged**
