### PR TITLE
Broaden compatibility for embedded platforms

### PR DESCRIPTION
**Pull request by coder0xff**
I'm working on compiling WebRTC on the Xtensa (ESP32s3) platform.

- Tokio was recently updated to support more platforms, but certain features are not available (and may never be). The "process" and "signal" features aren't used by WebRTC. Rather than use the "full" feature group, the relevant Cargo.toml's have been updated to list the set of features included in "full", excluding the "process" and "signal" features. WebRTC builds correctly against tokio with these changes.
- Migrates to the portable-atomic library from std::sync::atomic to support more platforms

### CODE REVIEW

**Comment by rainliu** [comment]
please make sure all checks are passed. Thanks.

**Comment by coder0xff** [comment]
> please make sure all checks are passed. Thanks.

I got `cargo test` passing and pushed, but the checks are now cleared so I can't see if any more failed. (I'm not familiar with GitHub's checks system.) Hopefully everything is good anyway.

**Comment by marcbrevoort-cyberhive** [comment]
I'd love to see this go in, if everything is okay with it. If not, it would be useful to know what's stopping it.

**Comment by coder0xff** [comment]
I'm rolling back the master branch on my fork so I can try the actions merging into my own master first. I'll close this PR in the meantime and re-open it once I can get past that step.

**Comment by coder0xff** [comment]
I had to create a new PR after rebasing. https://github.com/webrtc-rs/webrtc/pull/546

**Pull request closed without merging**
