### PR TITLE
use nextest for running test in CI

### PR DESCRIPTION
**Pull request by xnorpx**
https://nexte.st/

### CODE REVIEW

**Comment by xnorpx** [comment]
Doesn't seem to be stable as macos-latest fail. I let you guys decide if you want to use it or not.

**Comment by k0nserv** [comment]
I created https://github.com/webrtc-rs/webrtc/pull/258  which hopefully fixes it for good

**Comment by k0nserv** [comment]
258 is merged so you can rebase

**Comment by xnorpx** [comment]
running again

**Comment by k0nserv** [comment]
Will still fail due to the timer tests on Windows I reckon

**Comment by xnorpx** [comment]
> Will still fail due to the timer tests on Windows I reckon

yes, ubuntu mac should be enough now :)

**Pull request closed without merging**
