### PR TITLE
sctp: remove unnecessary drops and use precise padding

### PR DESCRIPTION
**Pull request by melekes**
Refs https://github.com/webrtc-rs/webrtc/pull/364 and https://github.com/webrtc-rs/webrtc/pull/367

cc @KillingSpark

### CODE REVIEW

**Review by algesten — CHANGES_REQUESTED** [review]
I don't believe this change will behave correctly.

Since all  the functions are `&self` rather than `&mut self`, we can potentially have multiple threads calling these functions at the same time.

The `let sem_lock` is a RAII guard that ensure the entire data structure is locked for the entire insertion. This is important in a case like this for loop.

https://github.com/webrtc-rs/webrtc/blob/daaf05d1021d8079ea1be4aa539e968726d18271/sctp/src/queue/pending_queue.rs#L120-L135

If two threads were competing in this loop, we would not be in "direct sequence". The code doc explains the relationship between the two locks.

>  The chunks of one fragmented message need to be put in direct sequence into the queue which the lock guarantees

Edit: provide correct link to loop

**Comment by melekes** [comment]
> The let sem_lock is a RAII guard that ensure the entire data structure is locked for the entire insertion. This is important in a case like this for loop.

I agree, but my point is we don't need to drop them since it will be done by Rust automatically.

**Comment by algesten** [comment]
> I agree, but my point is we don't need to drop them since it will be done by Rust automatically.

@melekes this is true. They do need to live for the entire scope though. So you can replace with `let _sem_lock = ` and just remove the `drop`.

**Comment by KillingSpark** [comment]
If you are fixing the padding anyways, there are a few some more places where get_padding_size is used alongside a vec![] call.

I think generalizing what I did in the packet marshal code would be a good idea:

```rust
static PADDING_BYTES: [u8; PADDING_MULTIPLE] = [0;PADDING_MULTIPLE];
pub(crate) fn get_padding(len: usize) -> &'static [u8] {
    &PADDING_BYTES[..get_padding_size()]
}
```

**Review by k0nserv — APPROVED** [review]

**Pull request merged**
