### PR TITLE
Custom `RTCRtpTransceiver` creating

### PR DESCRIPTION
**Pull request by logist322**
This PR provides API for creating custom `RTCRtpSender`, `RTCRtpReceiver` and `RTCRtpTransceiver` and adding `RTCRtpTransceiver` to `RTCPeerConnection`.

### CODE REVIEW

**Comment by k0nserv** [comment]
Can you talk a bit about why this is necessary? The spec compliant API should be enough I think

**Comment by logist322** [comment]
In general, it provides more advanced ways for working with `RTCRtpTransceiver`s. For example, in our project we need to pass the unique `Interceptor` for every `RTCRtpSender`.

**Comment by logist322** [comment]
@k0nserv it is ready for review

**Comment by logist322** [comment]
@k0nserv ping

**Comment by k0nserv** [comment]
> For example, in our project we need to pass the unique Interceptor for every RTCRtpSender.

Out of interest why is this needed? This isn't something that Pion provides atm so I'm thinking maybe there's another solve for your use case

**Comment by k0nserv** [comment]
@logist322 Can you talk a bit more about why this requires opening up this API? You can still register custom interceptors via the interceptor registry

**Review by rainliu — APPROVED** [review]

**Pull request merged**
