### PR TITLE
Integrate UDP mux support for ICE

### PR DESCRIPTION
**Pull request by k0nserv**
Sibling PR https://github.com/webrtc-rs/ice/pull/16

### CODE REVIEW

**Comment by rainliu** [comment]
I have merged v0.3.0 to master. Please rebase this PR to master. Thanks.

**Comment by k0nserv** [comment]
> I have merged v0.3.0 to master. Please rebase this PR to master. Thanks.

Will do

**Comment by rainliu** [comment]
@k0nserv, could you update this PR with ice 0.6.0? I am preparing for releasing webrtc 0.3.0 and like to include this change. Thanks.

**Comment by k0nserv** [comment]
Almost done, but I need https://github.com/webrtc-rs/ice/pull/20 to be merged. I moved the logic for checking the UDP port range into the `ice` crate instead.

**Comment by k0nserv** [comment]
Should this branch target `v0.3.0` or `master` by the way?

**Comment by rainliu** [comment]
just released ice v0.6.1.

master branch is fine.

**Pull request merged**
